export const plans = [
    {
        plan: "BASIC PLAN",
        price: "₦ 6000",
        features: [
            "Mpharma (Basic HMO)",
            "PIA VPN",
            "Prime Video",
            "Chat GPT",
            "Spotify",
            "Priority pass for card holders to Sterling bank and Activ8",
            "Bolt rides (3k coupon)",
            "iFitness Gym",
            "WasteBanc",
            "Greenleaf Gym",
            "Netflix NG",
        ],
    },
    {
        plan: "STANDARD PLAN",
        price: "₦ 10000",
        features: [
            "Mpharma (Basic HMO)",
            "Priority pass for card holders to Sterling bank and Activ8",
            "Spotify",
            "Hulu",
            "Bolt rides (3k coupon)",
            "HBO Max",
            "WasteBanc",
            "Showtime",
            "Netflix US",
            "iFitness Gym",
            "PIA VPN",
            "Greenleaf Gym",
            "Chat GPT",
        ],
    },
];
